**FORMAÇÃO CIENTISTA DE DADOS**

**Biblioteca Numpy**

In [11]:
#Importando a biblioteca 
import numpy as np

In [12]:
#Cria uma matriz unidimensional 
matrizUnidimensional = np.array([1,2,3,4,5])

print(matrizUnidimensional)
print(type(matrizUnidimensional))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
#Criando um array com um tipo específico (array como float de 64 bits e int de 32 bits)
matrizUnidimensionalFloat = np.array([1,2,3,4,5], dtype = np.float64)
print(matrizUnidimensionalFloat)
print(type(matrizUnidimensionalFloat))

print('\n')

matrizUnidimensionalInt = np.array([1,2,3,4,5], dtype = np.int32)
print(matrizUnidimensionalInt)
print(type(matrizUnidimensionalInt))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
#Mudar o tipo do array. Podemos transformar tipos de dados de arrays
matrizUnidimensionalTeste = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(matrizUnidimensionalTeste)

print('\n')

#Quando transformamos de float para int os valores são truncados
trocandoMatrizPraInt = matrizUnidimensionalTeste.astype(np.int32)
print(trocandoMatrizPraInt)

[ 1.4       3.6      -5.1       9.42      4.999999]


[ 1  3 -5  9  4]


In [15]:
#Podemos fazer o inverso também 
matrizInt = np.array([5,6,7,8])
print(matrizInt)

print('\n')

matrizIntPraFloat = matrizInt.astype(np.float64)
print(matrizIntPraFloat)

[5 6 7 8]


[5. 6. 7. 8.]


In [16]:
#Criando matriz de mais de uma dimensão (bidimensional)
matrizBidimensional = np.array([
                               [1,2,3,4],
                               [5,6,7,8],
                               [9,10,11,12]
                      ])

print(matrizBidimensional)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#Criando arrays azios tipificados (empty significa que não foram inicializados, não necessariamente vazios)
array = np.empty([3,2], dtype = int)
print(array)

print('\n')


#Criando uma matriz 4x3 com valores 0 
matrizComZeros = np.zeros([4,3])
print(matrizComZeros)

print('\n')


#Criando uma matriz 4x3 com valores 1
matrizComUns = np.ones([5,7])
print(matrizComUns)

print('\n')


#Criando matriz quadrada com diagonal principal com valores 1 e os outros valores zero
matrizDiagonal = np.eye(5)
print(matrizDiagonal)

[[-1871988352         467]
 [          0           0]
 [          1     7340137]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
from numpy import random
import numpy as np

#Valores aleatórios entre zero e um
valoresAleatorios = np.random.random((5))
print(valoresAleatorios)


print('\n')

#Valores aleatórios distribuídos normal contendo negativos
valoresAleatoriosComNegativos =  np.random.randn((5))
print(valoresAleatoriosComNegativos)


print('\n')


#Valores aleatórios 3x4
valoresAleatoriosUm = (10 * np.random.random((3,4)))
print(valoresAleatoriosUm)

[0.51672267 0.25640221 0.30555615 0.24579637 0.40191973]


[ 0.72151696  1.21170194  0.66562484 -0.42447556  1.06344247]


[[7.66809429 4.30117857 3.45818349 4.60878977]
 [6.3127971  3.58786699 0.42215133 5.33558851]
 [5.18383588 5.95588724 3.69352179 2.34591565]]


In [27]:
#Outra forma de gerar valores aleatórios (uso de semente)
gerandoValoresAleatorios = np.random.default_rng(1)
valoresAleatoriosDois = gerandoValoresAleatorios.random(3)
print(valoresAleatoriosDois)


print('\n')


#Gerando valores aleatórios inteiros
valoresAleatoriosTres = gerandoValoresAleatorios.integers(10, size=(3,4))
print(valoresAleatoriosTres)

[0.51182162 0.9504637  0.14415961]


[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [28]:
#O unique remove repetições
testandoUnique = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
testandoUnique = np.unique(testandoUnique)

print(testandoUnique)

[11 12 13 14 15 16 17 18 19 20]


In [29]:
#Funções específicas

#Criando uma matriz bidimensional K
k = np.array([ [17,22,43], [27,25,14], [15,24,32] ])
print(k)

print('\n')

#Mostra um valor específico da matriz
print(k[0][1])

print('\n')

#Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]


22


(3, 3)


In [30]:
#Funções matemáticas
#Mostra o maior valor da matriz K
print(k.max())

#Mostra o menor valor da matriz k
print(k.min())

#Mostra a soma dos valores da matriz K
print(k.sum())

#Mostra o valor da média dos valores da matriz k
print(k.mean())

#Mostra o valor do desvio padrão (standard deviation) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [31]:
#Funções universais aplicadas à todos os elementos

#Mostra o valor da raiz quadrada de todos os elementos
matrizFuncaoUniversal = np.array([1,4,9,16,25,36])
raizQuadradaMatriz = np.sqrt(matrizFuncaoUniversal) 
print(raizQuadradaMatriz)

print('\n')

#Mostra o valor exponencial de todos os valores
valorExponencialMatriz = np.exp(matrizFuncaoUniversal)
print(valorExponencialMatriz)

[1. 2. 3. 4. 5. 6.]


[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [35]:
#Extração de elementos da matriz
extraindoElementosMatriz = np.array([1,2,3,4,5,6])

print(extraindoElementosMatriz)
print('\n')

#Mostra o elemento da posição 2
posicaoDois = extraindoElementosMatriz[1]
print(posicaoDois)
print('\n')

#Mostra dois elementos do array criado a partir da posição 0
print(extraindoElementosMatriz[0:2])
print('\n')

#Mostra o array criado a partir da 2a posição até todo o restante do array
print(extraindoElementosMatriz[1:])
print('\n')

#Mostra o array criado a partir da antepenútima posição até o final 
print(extraindoElementosMatriz[-3:])

[1 2 3 4 5 6]


2


[1 2]


[2 3 4 5 6]


[4 5 6]


In [39]:
#Extração de linhas e colunas
extraindoLinhasEColunas = np.array([ [4,5], [6,7], [8,9] ])

print(extraindoLinhasEColunas)
print('\n')

#Mostra a primeira linha, todas as colunas
linha_1 = extraindoLinhasEColunas[0, :]

print(linha_1)
print('\n')


#Segunda linha, todas as colunas
linha_2 = extraindoLinhasEColunas[1, :]

print(linha_2)
print('\n')

#Terceira linha, todas as colunas
linha_3 = extraindoLinhasEColunas[2, :]

print(linha_3)
print('\n')

[[4 5]
 [6 7]
 [8 9]]


[4 5]


[6 7]


[8 9]




In [47]:
#Adição e multiplicação de matrizes
matrizUm = np.array([ [1,2], [3,4] ])
matrizDois = np.array([ [1,1], [1,1] ])
somaMatrizes = (matrizUm + matrizDois)

print('M1')
print(matrizUm)

print('\n')

print('M2')
print(matrizDois)

print('\n')

print('SOMA')
print(somaMatrizes)
print('\n')


multiplicacaoMatrizes = (matrizUm * matrizDois)

print('MULIPLICAÇÃO')
print(multiplicacaoMatrizes)
print('\n')


matrizTres = np.array([ [1,2], [3,4], [5,6] ])
MatrizQuatro = np.array([[2,1]])

somaMatrizesDiferentes = (matrizTres + MatrizQuatro)

print('SOMA DE MATRIZES DIFERENTES')
print(somaMatrizesDiferentes)

M1
[[1 2]
 [3 4]]


M2
[[1 1]
 [1 1]]


SOMA
[[2 3]
 [4 5]]


MULIPLICAÇÃO
[[1 2]
 [3 4]]


SOMA DE MATRIZES DIFERENTES
[[3 3]
 [5 5]
 [7 7]]


In [49]:
#Transposição, rearranja um conjunto de 15 elementos de 0 à 14 (em 3 linhas e 5 colunas)
testandoTransposicao = np.arange(15).reshape((3,5))

#Mostra a matriz transposta entre linha e coluna
print(testandoTransposicao)
print('\n')

transpondo = testandoTransposicao.T #Método T -> transforma linhas em colunas
print(transpondo)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [57]:
#Outra forma de fazer a transposição com o mesmo resultado
testandoTransposicaoDiferente = np.arange(15).reshape((3,5))

print(testandoTransposicaoDiferente)
print('\n')
                                          
#Rearranja um conjunto de 15 elementos mostrando a matriz transposta entre linha e coluna
transpondoDiferente = testandoTransposicaoDiferente.transpose((1,0))
print(transpondoDiferente)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [55]:
#Expressões lógicas
#Usando where, e criando matriz com valores aleatórios positivos e negativos
testandoExpressoesLogicas = np.random.randn(4,4)
print(testandoExpressoesLogicas)
print('\n')

#Criando matriz com valores booleanos baseado no array 'testandoExpressoesLogicas'
x = (testandoExpressoesLogicas > 0)
print(x)
print('\n')

#Criando matriz com valores -1 e 1 baseado nos valores do array 'x'
z = np.where(x > 0, 1, -1)
print(z)

[[-0.47827578  2.56577294  1.81162885 -0.80010782]
 [-0.3133488  -1.18349456  0.47637127 -0.47426663]
 [ 0.45857956  0.6279371  -0.93889355  1.57647798]
 [ 1.12845812 -1.03167876 -0.8957137   1.05412706]]


[[False  True  True False]
 [False False  True False]
 [ True  True False  True]
 [ True False False  True]]


[[-1  1  1 -1]
 [-1 -1  1 -1]
 [ 1  1 -1  1]
 [ 1 -1 -1  1]]
